### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by jxfish2** [projectcypress/cypress#1057]
For those of us who have worked with Linux and Unix for more than 20 years, it is common knowledge that you never install a program or application under a User's home directory.  Especially "root's" home directory.

The /opt filesystem is intended for 3rd party, out of the box, or off of the shelf applications.

The /usr/local filesystem is intended for internally developed applications, while /usr/local/bin is intended for individual, or very small command groupings and scripts.

Is there anything inside of the installed code under the /root home directory, that would need to be "tweaked" in order to relocate it to the /opt directory structure?

**Comment by rbclark** [comment]
I'm not exactly sure I understand what you are seeing installed to `/root`. By default our install scripts install the cypress code to `/opt/cypress` and install the cypress executable management tools to `/usr/bin/cypress`.

**Comment by jxfish2** [comment]
I was commenting on the /root/cypress-recipe install, the /root/.chef and /root/.berkshelf directory structures.  If the /root/cypress-recipe directory is an application, it should be under /opt, just as you correctly placed /opt/cypress.
The other question I have is this:  Does the cypress-recipe app need to run as root, or could it also run as the "cypress" user?
If it can be run as the cypress user (or some other functional account), then the two config directories should be under the generic / functional user account, and not under the root account.
Thanks for responding to the question.
Please understand that I really do appreciate the effort that you and your team have put forth to make this a viable application.
I sometimes get frustrated because in the Linux world, we have a lot of developers who like to code, and who want to contribute.  Their efforts are very much appreciated.
But, there are certain standards that must be adhered to, or you just end up with a big mess, and it makes troubleshooting more difficult.
Even within my own organization, I run into developers who have excellent ideas, but they do not understand why some of these standards exist.
Again, please do not take offense to my post.
I really appreciate what you are trying to do here.
Have a great day.

**Comment by rbclark** [comment]
Oops, sorry I assumed you meant the application itself, not the deployment scripts. You are welcome to place the `cypress-recipe` code anywhere you choose. The instructions do not call out a specific location since it can be run from anywhere and by any user as long as that user has `sudo` privileges. After install you are welcome to delete the whole `cypress-recipe` from your system as well as uninstall the `chefdk` if you choose, they are not necessary for continued operation of Cypress. The `cypress-recipe` needs to either run as `root` or with `sudo` so that it has permission to install the `cypress` package.
