### ISSUE TITLE
QRDA 1 Test Exection Remains In Progress 

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#462]
QRDA 1 Test Exection Remains In Progress all the time. Cypress 3.0Alpha4
![untitled](https://cloud.githubusercontent.com/assets/18002170/15111062/5060beb8-1602-11e6-8d6b-92df8f6ccf10.png)

**Comment by ssayer** [comment]
Sudhir, can you try upgrading to the latest release (alpha 4) and see if that fixes the issue? These upgrade instructions should still work even though though it's for the alpha 3 to alpha 4 release.

https://github.com/projectcypress/cypress/wiki/Cypress-3.0.0-Alpha3-to-Alpha4-Upgrade-Instructions

**Comment by sudhir-nair** [comment]
I have already installed Alpha 4 and working on it. This issue doesn't seem to be fixed in alpha4.

**Comment by ssayer** [comment]
This could be caused by an invalid upload causing the calculation job to hang. We expect to deploy a new build by this Thursday that should address this problem.

**Comment by ssayer** [comment]
Also, can you attach the QRDA files you uploaded that caused this issue?

**Comment by sudhir-nair** [comment]
[QRDAI.txt](https://github.com/projectcypress/cypress/files/255204/QRDAI.txt)

Just  rename .txt to .zip. Actual files will be found. These files has been already validate on Online Cypress Validator.

**Comment by dczulada** [comment]
Thanks for the attached files.

This does look like it is an issue with the calculation of the QRDA files you've attached.  We have already made the Cypress calculation engine a little more fault tolerant for the release later this week.

With respect to the files you've attached, the patients are not making it into the IPP for the measure (which is what caused the calculation engine to crash) because the patients do not have the ordinality recorded for their "Diagnosis, Active: Acute Myocardial Infarction (AMI)."

Here is the measure logic that require the ordinality to be present:
_Diagnosis, Active: Acute Myocardial Infarction (AMI) (ordinality: Principal)" starts during Occurrence A of $EncounterInpatient_

As a result, the AMI diagnosis should include the following.

`<priorityCode  code="63161005" codeSystem="2.16.840.1.113883.6.96" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.14"/>`

This priority Code specified in the QRDA Cat Implementation Guide
_MAY contain zero or one [0..1] priorityCode (CONF:1140-14547)._

Hope this helps.
-Dave Czulada

**Comment by ssayer** [comment]
Sudhir,

This issue should be resolved as of Cypress Alpha 6. You can get the new VM/AMI by following the install instructions: https://github.com/projectcypress/cypress/wiki/Cypress-3.0.0-Install-Instructions
