### ISSUE TITLE
For CMS172 the patient should be denominator exclusion but its meeting performance

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#525]
For CMS172(a)
[2_1_N SCIP.txt](https://github.com/projectcypress/cypress/files/327835/2_1_N.SCIP.txt)
 the patient should be denominator exclusion as per cypress, but as per data its not meeting any exclusion criteria and hence meeting performance. According to us the patient should pass the below condition for exclusion
OR: "Procedure, Performed: General or Neuraxial Anesthesia" satisfies any ◾<= 4 day(s) ends before start of "Occurrence A of Procedure, Performed: General or Neuraxial Anesthesia" 
◾<= 4 day(s) starts after end of "Occurrence A of Procedure, Performed: General or Neuraxial Anesthesia
We found out the difference between the above 2 proc is 6 days; whereas measure says it should be 4 days
Please find attached the patients file
[2_1_N SCIP.txt](https://github.com/projectcypress/cypress/files/327841/2_1_N.SCIP.txt)

**Comment by souravkhemka** [comment]
Any update on this ticket?

**Comment by dczulada** [comment]
Hi

This patient actually falls into the DENEX due to the logic statement below

OR: "Medication, Administered: IV, IM, PO Antimicrobial Medications (route: Substance or Medication Administration Route IV, oral or IM)" > 1440 minute(s) starts before start of ("Occurrence A of Procedure, Performed: General or Neuraxial Anesthesia" during Occurrence A of $EncounterInpatient )

The mediation (code 197512) was administered on 20140509080000.  Which is more than 1440 (24 hours) before the procedure (code 24277005) on 20140514080000.

-Dave Czulada
