### ISSUE TITLE
For some measure there is no templated id in the device order ACT for patients

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#536]
For measure id CMS108,CMS114,CMS190, some of the patients have device order tag which do not have any templateid in the cypress data; due to this the QRDA files are not consumed in our environment.
Please find attached the patients files
[2_8 N_N VTE.txt](https://github.com/projectcypress/cypress/files/329707/2_8.N_N.VTE.txt)
[3_11 N_N VTE.txt](https://github.com/projectcypress/cypress/files/329706/3_11.N_N.VTE.txt)

![devicepordertemplatemissing](https://cloud.githubusercontent.com/assets/20084778/16300048/59fb9322-395b-11e6-9f18-d29785335946.png)

**Comment by souravkhemka** [comment]
Any update on this ticket?

**Comment by dczulada** [comment]
Hi,

This is actually intentional. The QRDA spec does not allow for Device Order - Not Done, so this is a workaround until the spec issue can be resolved.

For more information please see:
https://jira.oncprojectracking.org/browse/QRDA-176
http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=696

Thanks,
Dave Czulada
