### ISSUE TITLE
CMS185 has IPP configured as 2013 spec and Cypress data is per 2015 spec

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#614]
Hi,
The below ticket says that for CMS 185, the IPP is considered as of 2013 version
https://oncprojectracking.healthit.gov/support/browse/CQM-1142

But the data now Cypress gives is as per 2015 IPP version.
 So in this case, the patients are not qualifying IPP as of current cypress data

**Comment by souravkhemka** [comment]
As per 2013, 
"Diagnosis, Active: Gestational age >= 37 weeks" starts during "Occurrence A of Encounter, Performed: Encounter Inpatient""
the first statement of IPP is of Diagnosis whereas as per 2014 version,
◾"AND: "Physical Exam, Performed: Gestational age >= 37 weeks (result >= 37 week(s))" starts during Occurrence A of $EncounterInpatient "
 the same statement is of Procedure

**Comment by dczulada** [comment]
I'm not sure I follow.

Are you stating that a patient for the 2013 measure would not qualify for the 2015 IPP?  Or that the 2015 Cypress patient doesn't have the data necessary for the 2013 IPP?  The Cypress patients are developed to be calculated against the current year (i.e. 2015 patient for 2015 measure)

Cypress is validating the measure as written, and does not account for submission workaround discussed in the referenced JIRA ticket.  Please note the following from the referenced ticket:

"CMS suggests eligible hospitals participating in the Medicare & Medicaid EHR Incentive Programs not select NQF 0176: Healthy Term Newborn as one of their electronic clinical quality measures (eCQMs) for meaningful use. The measure will no longer be maintained since the measure steward has submitted a substantially changed measure to NQF for endorsement."
